### PR TITLE
Switch from `ansi-wl-pprint` to `prettyprinter` package.

### PR DESCRIPTION
**Pull request by brianhuffman**
This patch includes and adapts to the following submodule PRs:
- GaloisInc/what4#77 "prettyprinter"
- GaloisInc/crucible#586 "prettyprinter"

### CODE REVIEW

**Comment by brianhuffman** [comment]
It looks like the CI builds are failing for an unrelated reason:
```
  Error: Unable to process command '::add-path::/opt/ghc/8.6.5/bin' successfully.
  Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
``

**Comment by joehendrix** [comment]
Maybe @jared-w is the right person to weigh in on `actions/setup-haskell`.  I'd guess this would be a simple fix to update that action, but don't have a experience with it.

**Comment by brianhuffman** [comment]
GaloisInc/macaw#178 depends on this PR to pass CI, so I'd like to get this one merged before merging that one.

**Comment by jared-w** [comment]
Long story short, the README for `setup-haskell` used the `v1.1` tag as that tag is the one that introduced some new features like the outputs. I had expected it to be updated along with the v1 tag, but it never was. So the README should've used the `v1` tag in its examples.

**Review by travitch — APPROVED** [review]
Looks good to me - thanks!

**Comment by brianhuffman** [comment]
Thanks for the fix, @jared-w!

**Pull request merged**
